{{- if and .Values.multiCluster.enabled .Values.multiCluster.kubeconfig.fromContent .Values.multiCluster.kubeconfig.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kite.fullname" . }}-kubeconfig
  labels:
    {{- include "kite.labels" . | nindent 4 }}
stringData:
  kubeconfig: |-
{{- .Values.multiCluster.kubeconfig.content | nindent 4 }}
{{- end }}
