apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kite.fullname" . }}-secret
  labels:
    {{- include "kite.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
  {{- if .Values.basicAuth.enabled }}
  KITE_USERNAME: {{ .Values.basicAuth.username | b64enc | quote }} 
  KITE_PASSWORD: {{ .Values.basicAuth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.oauth.enabled }}
  {{- range $provider, $cfg := .Values.oauth.providers }}
  {{- $PROVIDER := upper $provider }}
  {{- if $cfg.clientId }}
  {{ printf "%s_CLIENT_ID" $PROVIDER }}: {{ $cfg.clientId | b64enc | quote }}
  {{- end }}
  {{- if $cfg.clientSecret }}
  {{ printf "%s_CLIENT_SECRET" $PROVIDER }}: {{ $cfg.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if $cfg.authUrl }}
  {{ printf "%s_AUTH_URL" $PROVIDER }}: {{ $cfg.authUrl | b64enc | quote }}
  {{- end }}
  {{- if $cfg.tokenUrl }}
  {{ printf "%s_TOKEN_URL" $PROVIDER }}: {{ $cfg.tokenUrl | b64enc | quote }}
  {{- end }}
  {{- if $cfg.userInfoUrl }}
  {{ printf "%s_USERINFO_URL" $PROVIDER }}: {{ $cfg.userInfoUrl | b64enc | quote }}
  {{- end }}
  {{- if $cfg.scopes }}
  {{ printf "%s_SCOPES" $PROVIDER }}: {{ $cfg.scopes | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}