name: deploy test env

permissions:
  contents: read
  packages: write

concurrency:
  group: deploy-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build and Push Preview Docker Image"]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy Test Env
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'zxh326' }}

    steps:
      - name: restart kite deployment
        env:
          KITE_HOST: ${{ secrets.KITE_TEST_HOST }}
          KITE_AUTH: ${{ secrets.KITE_TEST_AUTH }}
        run: |
          RESTART_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          curl -X PATCH "$KITE_HOST/api/v1/deployments/kite/kite" \
            -H "Authorization: $KITE_AUTH" \
            -H "Content-Type: application/json" \
            -d "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"kite.kubernetes.io/restartedAt\":\"$RESTART_TIME\"}}}}}"
